const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DBKEY='auditabu2026.v2', CKEY='auditabu2026.candidates'; let db=JSON.parse(localStorage.getItem(DBKEY)||'{"bus":[],"pending":{},"alerts":[]}'); let candidates=JSON.parse(localStorage.getItem(CKEY)||'{}');
const offices={'1':'Presidente','3':'Governador','5':'Senador','6':'Deputado Federal','7':'Deputado Estadual/Distrital'};
function save(){localStorage.setItem(DBKEY,JSON.stringify(db));render()}; function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function pairs(txt){let out=[]; for(const p of txt.trim().split(/\s+/)){let i=p.indexOf(':'); if(i>0)out.push([p.slice(0,i),p.slice(i+1)])} return out}
function vals(ps,k){return ps.filter(x=>x[0]===k).map(x=>x[1])} function val(ps,k){return vals(ps,k)[0]||''}
function parseSeq(txt){let m=txt.match(/(?:^|\s)QRBU:(\d+):(\d+)/); return m?{total:+m[1],idx:+m[2]}:null}
function pendingKey(txt){let ps=pairs(txt); return [val(ps,'PLEI'),val(ps,'UF'),val(ps,'MUNI'),val(ps,'ZONA'),val(ps,'SECA'),val(ps,'IDUE')].join('|') || ('unknown-'+Date.now())}
function parseBU(chunks){let text=chunks.join(' '), ps=pairs(text), meta={uf:val(ps,'UF'),muni:val(ps,'MUNI'),zona:val(ps,'ZONA'),secao:val(ps,'SECA'),urna:val(ps,'IDUE'),turno:val(ps,'TURNO'),pleito:val(ps,'PLEI'),comp:val(ps,'COMP'),hashes:vals(ps,'HASH'),assi:val(ps,'ASSI')}; let votes={}, current=''; for(let [k,v] of ps){if(k==='CARG'){current=v;votes[current]??={nominal:{},branco:0,nulo:0,total:0,legenda:{}}} else if(current){if(k==='BRAN')votes[current].branco+=+v||0; else if(k==='NULO')votes[current].nulo+=+v||0; else if(k==='TOTC')votes[current].total+=+v||0; else if(/^\d+$/.test(k))votes[current].nominal[k]=(votes[current].nominal[k]||0)+(+v||0)}} return {meta,votes,rawChunks:chunks,created:new Date().toISOString()}}
function buId(b){return [b.meta.pleito,b.meta.uf,b.meta.muni,b.meta.zona,b.meta.secao,b.meta.urna,b.meta.turno].join('|')}
async function acceptChunk(txt){let seq=parseSeq(txt); if(!seq)throw Error('QRBU:n:x não encontrado. Confirme que o conteúdo é de um BU.'); let key=pendingKey(txt), p=db.pending[key]||{total:seq.total,chunks:{}}; p.total=seq.total;p.chunks[seq.idx]=txt.trim();db.pending[key]=p; if(Object.keys(p.chunks).length<p.total){save();return `QR ${seq.idx}/${p.total} recebido. Faltam ${p.total-Object.keys(p.chunks).length}.`}; let chunks=[];for(let i=1;i<=p.total;i++){if(!p.chunks[i])throw Error(`Falta o QR ${i}/${p.total}`);chunks.push(p.chunks[i])} let b=parseBU(chunks); b.id=buId(b); if(db.bus.some(x=>x.id===b.id)){delete db.pending[key];db.alerts.push({type:'duplicado',id:b.id,at:new Date().toISOString()});save();return 'BU já cadastrado: não foi somado novamente.'} b.integrity=b.meta.hashes.length?'HASH presente — cadeia registrada':'HASH não informado/identificado'; b.signature=b.meta.assi?'ASSI presente — não verificada':'não identificada'; db.bus.push(b);delete db.pending[key];save();return 'BU contabilizado com sucesso.'}
function candidateName(cargo,num,uf){return candidates[[cargo,num,uf].join('|')]||candidates[[cargo,num,''].join('|')]||`Opção ${num}`}
function render(){ $('#mBU').textContent=db.bus.length;$('#mSec').textContent=new Set(db.bus.map(b=>[b.meta.uf,b.meta.zona,b.meta.secao].join('|'))).size;$('#mPend').textContent=Object.values(db.pending).reduce((a,p)=>a+Math.max(0,p.total-Object.keys(p.chunks).length),0);$('#mAlert').textContent=db.alerts.length;
 let cargos=[...new Set(db.bus.flatMap(b=>Object.keys(b.votes)))],oldCargo=$('#office').value;$('#office').innerHTML=cargos.length?cargos.map(c=>`<option value="${esc(c)}">${esc(offices[c]||('Cargo '+c))}</option>`).join(''):'<option value="">Sem dados</option>';if(cargos.includes(oldCargo))$('#office').value=oldCargo; let ufs=[...new Set(db.bus.map(b=>b.meta.uf).filter(Boolean))].sort();let old=$('#uf').value;$('#uf').innerHTML='<option value="">Todas</option>'+ufs.map(x=>`<option>${esc(x)}</option>`).join('');$('#uf').value=ufs.includes(old)?old:''; renderTotals();
 $('#bus').innerHTML=db.bus.slice().reverse().map(b=>`<tr><td>${esc(b.meta.uf)}</td><td>${esc(b.meta.muni)}</td><td>${esc(b.meta.zona)}</td><td>${esc(b.meta.secao)}</td><td>${esc(b.meta.urna)}</td><td>${esc(b.meta.turno)}</td><td><span class="pill good">${esc(b.integrity)}</span></td><td><span class="pill warn">${esc(b.signature)}</span></td><td><button class="btn danger del" data-id="${esc(b.id)}">Excluir</button></td></tr>`).join(''); $$('.del').forEach(x=>x.onclick=()=>{if(confirm('Excluir este BU da base local e recalcular os totais?')){db.bus=db.bus.filter(b=>b.id!==x.dataset.id);save()}})}
function renderTotals(){let cargo=$('#office').value,uf=$('#uf').value,z=$('#zone').value.trim(), rows=db.bus.filter(b=>(!uf||b.meta.uf===uf)&&(!z||b.meta.zona===z)), t={},br=0,nu=0,total=0;for(let b of rows){let v=b.votes[cargo];if(!v)continue;for(let [n,q] of Object.entries(v.nominal))t[n]=(t[n]||0)+q;br+=v.branco;nu+=v.nulo;total+=v.total}let nominal=Object.values(t).reduce((a,b)=>a+b,0);$('#totals').innerHTML=Object.entries(t).sort((a,b)=>b[1]-a[1]).map(([n,q])=>`<tr><td>${esc(n)}</td><td>${esc(candidateName(cargo,n,uf))}</td><td><b>${q.toLocaleString('pt-BR')}</b></td><td>${nominal?(100*q/nominal).toFixed(2):'0.00'}%</td></tr>`).join('');$('#summary').textContent=`${rows.length} BU(s) filtrados • Nominais: ${nominal.toLocaleString('pt-BR')} • Brancos: ${br.toLocaleString('pt-BR')} • Nulos: ${nu.toLocaleString('pt-BR')} • TOTC informado: ${total.toLocaleString('pt-BR')}`}
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.className='btn secondary');b.className='btn primary';$$('.tab').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.tab).classList.add('active')});
$('#process').onclick=async()=>{try{$('#msg').className='ok';$('#msg').textContent=await acceptChunk($('#raw').value);$('#raw').value=''}catch(e){$('#msg').className='err';$('#msg').textContent=e.message}};$('#clearRaw').onclick=()=>$('#raw').value='';$('#office').onchange=renderTotals;$('#uf').onchange=renderTotals;$('#zone').oninput=renderTotals;
let stream=null,timer=null,lastCode='',lastAt=0;
function stopCamera(){if(timer){clearInterval(timer);timer=null}stream?.getTracks().forEach(t=>t.stop());stream=null;$('#video').srcObject=null;$('#video').classList.add('hidden')}
async function onDecoded(raw){if(!raw)return;let now=Date.now();if(raw===lastCode&&now-lastAt<2500)return;lastCode=raw;lastAt=now;try{let r=await acceptChunk(raw);$('#cameraMsg').textContent=r;navigator.vibrate?.(100)}catch(e){$('#cameraMsg').textContent=e.message}}
$('#camera').onclick=async()=>{try{if(!window.isSecureContext)throw Error('A câmera exige HTTPS.');if(!navigator.mediaDevices?.getUserMedia)throw Error('Este navegador não disponibiliza acesso à câmera. Use “Ler QR por foto”.');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});let v=$('#video');v.srcObject=stream;v.classList.remove('hidden');await v.play();$('#cameraMsg').textContent='Câmera ativa. Aponte para o QR Code do BU e mantenha-o centralizado.';let canvas=$('#scanCanvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});timer=setInterval(async()=>{try{if(v.readyState<2)return;let w=v.videoWidth,h=v.videoHeight;if(!w||!h)return;let scale=Math.min(1,900/w);canvas.width=Math.round(w*scale);canvas.height=Math.round(h*scale);ctx.drawImage(v,0,0,canvas.width,canvas.height);let im=ctx.getImageData(0,0,canvas.width,canvas.height);if(typeof jsQR==='function'){let code=jsQR(im.data,im.width,im.height,{inversionAttempts:'attemptBoth'});if(code?.data)await onDecoded(code.data)}else{$('#cameraMsg').textContent='Leitor QR não carregado. Verifique a internet ou use “Ler QR por foto”.'}}catch(e){}},300)}catch(e){stopCamera();$('#cameraMsg').textContent=e.name==='NotAllowedError'?'Permissão da câmera negada. Autorize a câmera para este site e recarregue a página.':e.message}};
$('#stop').onclick=stopCamera;
$('#qrPhoto').onchange=async e=>{try{let f=e.target.files?.[0];if(!f)return;if(typeof jsQR!=='function')throw Error('O leitor QR não carregou.');let bmp=await createImageBitmap(f),canvas=$('#scanCanvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});let scale=Math.min(1,1600/bmp.width);canvas.width=Math.round(bmp.width*scale);canvas.height=Math.round(bmp.height*scale);ctx.drawImage(bmp,0,0,canvas.width,canvas.height);let im=ctx.getImageData(0,0,canvas.width,canvas.height),code=jsQR(im.data,im.width,im.height,{inversionAttempts:'attemptBoth'});if(!code?.data)throw Error('Não consegui identificar um QR Code nessa foto.');await onDecoded(code.data)}catch(err){$('#cameraMsg').textContent=err.message}finally{e.target.value=''}};
function download(name,type,text){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#json').onclick=()=>download('auditabu-2026.json','application/json',JSON.stringify(db,null,2));$('#csv').onclick=()=>{let r=['UF,MUNICIPIO,ZONA,SECAO,URNA,TURNO,CARGO,NUMERO,VOTOS'];for(let b of db.bus)for(let[c,v]of Object.entries(b.votes))for(let[n,q]of Object.entries(v.nominal))r.push([b.meta.uf,b.meta.muni,b.meta.zona,b.meta.secao,b.meta.urna,b.meta.turno,c,n,q].join(','));download('auditabu-2026.csv','text/csv;charset=utf-8','\ufeff'+r.join('\n'))};$('#wipe').onclick=()=>{if(confirm('Apagar TODOS os BUs armazenados neste aparelho?')){db={bus:[],pending:{},alerts:[]};save()}};
$('#candidateTemplate').onclick=()=>download('modelo-candidatos.csv','text/csv;charset=utf-8','\ufeffcargo,numero,nome,partido,uf\n1,00,Nome do candidato,PARTIDO,BR\n');$('#candidateFile').onchange=async e=>{let f=e.target.files?.[0];if(!f)return;let txt=await f.text(),lines=txt.replace(/^\ufeff/,'').split(/\r?\n/).filter(Boolean),head=lines.shift().split(',').map(x=>x.trim().toLowerCase());for(let l of lines){let a=l.split(','),o=Object.fromEntries(head.map((h,i)=>[h,(a[i]||'').trim()]));if(o.cargo&&o.numero)candidates[[o.cargo,o.numero,o.uf||''].join('|')]=`${o.nome||('Opção '+o.numero)}${o.partido?' — '+o.partido:''}`}localStorage.setItem(CKEY,JSON.stringify(candidates));$('#candidateMsg').textContent=`Cadastro carregado: ${Object.keys(candidates).length} registros.`;renderTotals()};$('#clearCandidates').onclick=()=>{candidates={};localStorage.removeItem(CKEY);$('#candidateMsg').textContent='Cadastro removido.';renderTotals()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();