const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DBKEY='auditabu2026.v2', CKEY='auditabu2026.candidates'; let db=JSON.parse(localStorage.getItem(DBKEY)||'{"bus":[],"pending":{},"alerts":[]}'); let candidates=JSON.parse(localStorage.getItem(CKEY)||'{}');
const offices={'1':'Presidente','3':'Governador','5':'Senador','6':'Deputado Federal','7':'Deputado Estadual/Distrital'};
function save(){localStorage.setItem(DBKEY,JSON.stringify(db));render()}; function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function pairs(txt){let out=[]; for(const p of txt.trim().split(/\s+/)){let i=p.indexOf(':'); if(i>0)out.push([p.slice(0,i),p.slice(i+1)])} return out}
function vals(ps,k){return ps.filter(x=>x[0]===k).map(x=>x[1])} function val(ps,k){return vals(ps,k)[0]||''}
function parseSeq(txt){let m=txt.match(/(?:^|\s)QRBU:(\d+):(\d+)/); return m?{total:+m[1],idx:+m[2]}:null}
function pendingKey(txt){let ps=pairs(txt); return [val(ps,'PLEI'),val(ps,'UF'),val(ps,'MUNI'),val(ps,'ZONA'),val(ps,'SECA'),val(ps,'IDUE')].join('|') || ('unknown-'+Date.now())}
function parseBU(chunks){let text=chunks.join(' '), ps=pairs(text), meta={uf:val(ps,'UF'),muni:val(ps,'MUNI'),zona:val(ps,'ZONA'),secao:val(ps,'SECA'),urna:val(ps,'IDUE'),turno:val(ps,'TURNO'),pleito:val(ps,'PLEI'),comp:val(ps,'COMP'),hashes:vals(ps,'HASH'),assi:val(ps,'ASSI')}; let votes={}, current=''; for(let [k,v] of ps){if(k==='CARG'){current=v;votes[current]??={nominal:{},branco:0,nulo:0,total:0,legenda:{}}} else if(current){if(k==='BRAN')votes[current].branco+=+v||0; else if(k==='NULO')votes[current].nulo+=+v||0; else if(k==='TOTC')votes[current].total+=+v||0; else if(/^\d+$/.test(k))votes[current].nominal[k]=(votes[current].nominal[k]||0)+(+v||0)}} return {meta,votes,rawChunks:chunks,created:new Date().toISOString()}}
function buId(b){return [b.meta.pleito,b.meta.uf,b.meta.muni,b.meta.zona,b.meta.secao,b.meta.urna,b.meta.turno].join('|')}
const SUPABASE_URL='https://mhdinwlgubmxyjldjkqb.supabase.co';
const SUPABASE_KEY='sb_publishable_P4iFEgWjDRE5Pdq1y8OLIw_TY7kQh5k';
const DEVICE_KEY='auditabu2026.device';let deviceId=localStorage.getItem(DEVICE_KEY);if(!deviceId){deviceId=(crypto.randomUUID?.()||('dev-'+Date.now()+'-'+Math.random().toString(36).slice(2)));localStorage.setItem(DEVICE_KEY,deviceId)}
async function sb(path,opt={}){let r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{...opt,headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY,'Content-Type':'application/json',...(opt.headers||{})}});if(!r.ok)throw Error('Falha na sincronização central ('+r.status+').');let t=await r.text();return t?JSON.parse(t):null}
function centralPayload(b){let rows=[];for(const[c,v]of Object.entries(b.votes)){for(const[n,q]of Object.entries(v.nominal||{}))rows.push({cargo:c,numero:n,votos:+q||0});rows.push({cargo:c,numero:'BRAN',votos:+v.branco||0},{cargo:c,numero:'NULO',votos:+v.nulo||0},{cargo:c,numero:'TOTC',votos:+v.total||0})}return {bu_uid:b.id,pleito:b.meta.pleito,uf:b.meta.uf,municipio:b.meta.muni,zona:b.meta.zona,secao:b.meta.secao,urna:b.meta.urna,turno:b.meta.turno,integrity_status:b.integrity,signature_status:b.signature,raw_chunks:b.rawChunks,payload:b,device_id:deviceId,captured_at:b.created,votes:rows}}
async function ingestCentral(b){return sb('rpc/ingest_bu',{method:'POST',body:JSON.stringify({p_bu:centralPayload(b)})})}
async function refreshCentral(){try{for(const b of db.bus.filter(x=>x.syncPending)){try{let r=await ingestCentral(b);if(r?.status==='inserted'||r?.status==='duplicate')b.syncPending=false}catch(e){}}let rows=await sb('boletins?select=payload&order=received_at.asc');let remote=(rows||[]).map(x=>x.payload).filter(x=>x?.id);let localPending=db.bus.filter(x=>x.syncPending);let map=new Map(remote.map(x=>[x.id,x]));for(let x of localPending)if(!map.has(x.id))map.set(x.id,x);db.bus=[...map.values()];localStorage.setItem(DBKEY,JSON.stringify(db));render();$('#syncState')&&($('#syncState').textContent='Base central sincronizada • '+new Date().toLocaleTimeString('pt-BR'))}catch(e){$('#syncState')&&($('#syncState').textContent='Sem conexão com a base central — dados locais preservados.')}}
async function acceptChunk(txt){let seq=parseSeq(txt);if(!seq)throw Error('QRBU:n:x não encontrado. Confirme que o conteúdo é de um BU.');let key=pendingKey(txt),p=db.pending[key]||{total:seq.total,chunks:{}};p.total=seq.total;p.chunks[seq.idx]=txt.trim();db.pending[key]=p;if(Object.keys(p.chunks).length<p.total){save();return `QR ${seq.idx}/${p.total} recebido. Faltam ${p.total-Object.keys(p.chunks).length}.`}let chunks=[];for(let i=1;i<=p.total;i++){if(!p.chunks[i])throw Error(`Falta o QR ${i}/${p.total}`);chunks.push(p.chunks[i])}let b=parseBU(chunks);b.id=buId(b);if(db.bus.some(x=>x.id===b.id&&!x.syncPending)){delete db.pending[key];db.alerts.push({type:'duplicado',id:b.id,at:new Date().toISOString()});save();return 'BU já cadastrado: não foi somado novamente.'}b.integrity=b.meta.hashes.length?'HASH presente — cadeia registrada':'HASH não informado/identificado';b.signature=b.meta.assi?'ASSI presente — não verificada':'não identificada';try{let r=await ingestCentral(b);delete db.pending[key];if(r?.status==='duplicate'){db.alerts.push({type:'duplicado',id:b.id,at:new Date().toISOString()});await refreshCentral();return 'BU já cadastrado: não foi somado novamente.'}b.syncPending=false;db.bus=db.bus.filter(x=>x.id!==b.id);db.bus.push(b);save();return 'BU contabilizado com sucesso.'}catch(e){b.syncPending=true;db.bus=db.bus.filter(x=>x.id!==b.id);db.bus.push(b);delete db.pending[key];save();return 'BU salvo neste aparelho. Sem conexão com a base central; sincronização pendente.'}}
function candidateInfo(cargo,num,uf){let v=candidates[[cargo,num,uf].join('|')]||candidates[[cargo,num,''].join('|')]||'';if(!v)return {nome:`Opção ${num}`,partido:''};let p=v.split(' — ');return {nome:p[0]||`Opção ${num}`,partido:p.slice(1).join(' — ')||''}}
function candidateName(cargo,num,uf){let c=candidateInfo(cargo,num,uf);return c.partido?`${c.nome} — ${c.partido}`:c.nome}
function render(){ $('#mBU').textContent=db.bus.length;$('#mSec').textContent=new Set(db.bus.map(b=>[b.meta.uf,b.meta.zona,b.meta.secao].join('|'))).size;$('#mPend').textContent=Object.values(db.pending).reduce((a,p)=>a+Math.max(0,p.total-Object.keys(p.chunks).length),0);$('#mAlert').textContent=db.alerts.length;
 let cargos=[...new Set(db.bus.flatMap(b=>Object.keys(b.votes)))],oldCargo=$('#office').value;$('#office').innerHTML=cargos.length?cargos.map(c=>`<option value="${esc(c)}">${esc(offices[c]||('Cargo '+c))}</option>`).join(''):'<option value="">Sem dados</option>';if(cargos.includes(oldCargo))$('#office').value=oldCargo; let ufs=[...new Set(db.bus.map(b=>b.meta.uf).filter(Boolean))].sort();let old=$('#uf').value;$('#uf').innerHTML='<option value="">Todas</option>'+ufs.map(x=>`<option>${esc(x)}</option>`).join('');$('#uf').value=ufs.includes(old)?old:''; renderTotals();
 $('#bus').innerHTML=db.bus.slice().reverse().map(b=>`<tr><td>${esc(b.meta.uf)}</td><td>${esc(b.meta.muni)}</td><td>${esc(b.meta.zona)}</td><td>${esc(b.meta.secao)}</td><td>${esc(b.meta.urna)}</td><td>${esc(b.meta.turno)}</td><td><span class="pill good">${esc(b.integrity)}</span></td><td><span class="pill warn">${esc(b.signature)}</span></td><td>${b.syncPending?'<span class="pill warn">Pendente</span>':'<span class="pill good">Central</span>'}</td></tr>`).join('')}
function renderTotals(){let cargo=$('#office').value,uf=$('#uf').value,z=$('#zone').value.trim(), rows=db.bus.filter(b=>(!uf||b.meta.uf===uf)&&(!z||b.meta.zona===z)), t={},br=0,nu=0,total=0;for(let b of rows){let v=b.votes[cargo];if(!v)continue;for(let [n,q] of Object.entries(v.nominal))t[n]=(t[n]||0)+q;br+=v.branco;nu+=v.nulo;total+=v.total}let nominal=Object.values(t).reduce((a,b)=>a+b,0);$('#totals').innerHTML=Object.entries(t).sort((a,b)=>b[1]-a[1]).map(([n,q])=>`<tr><td>${esc(n)}</td><td>${esc(candidateName(cargo,n,uf))}</td><td><b>${q.toLocaleString('pt-BR')}</b></td><td>${nominal?(100*q/nominal).toFixed(2):'0.00'}%</td></tr>`).join('');$('#summary').textContent=`${rows.length} BU(s) filtrados • Nominais: ${nominal.toLocaleString('pt-BR')} • Brancos: ${br.toLocaleString('pt-BR')} • Nulos: ${nu.toLocaleString('pt-BR')} • TOTC informado: ${total.toLocaleString('pt-BR')}`}
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.className='btn secondary');b.className='btn primary';$$('.tab').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.tab).classList.add('active')});
$('#process').onclick=async()=>{try{$('#msg').className='ok';$('#msg').textContent=await acceptChunk($('#raw').value);$('#raw').value=''}catch(e){$('#msg').className='err';$('#msg').textContent=e.message}};$('#clearRaw').onclick=()=>$('#raw').value='';$('#office').onchange=renderTotals;$('#uf').onchange=renderTotals;$('#zone').oninput=renderTotals;
let stream=null,timer=null,lastCode='',lastAt=0,scanPaused=false,requireClearFrame=false,clearFrames=0;
function stopCamera(){if(timer){clearInterval(timer);timer=null}stream?.getTracks().forEach(t=>t.stop());stream=null;$('#video').srcObject=null;$('#video').classList.add('hidden')}
async function onDecoded(raw){if(!raw||scanPaused||requireClearFrame)return;let now=Date.now();if(raw===lastCode&&now-lastAt<2500)return;lastCode=raw;lastAt=now;scanPaused=true;try{let r=await acceptChunk(raw);$('#cameraMsg').textContent=r;navigator.vibrate?.(100);if(r==='BU contabilizado com sucesso.'){alert('CAPTURA CONCLUÍDA\n\nBoletim de Urna registrado com sucesso.\n\nClique em OK e a câmera continuará aberta para o próximo BU.');lastCode=raw;lastAt=Date.now();requireClearFrame=true;clearFrames=0;$('#cameraMsg').textContent='Câmera ativa. Afaste o QR da câmera para liberar a próxima leitura.';}else if(r.startsWith('BU já cadastrado')){alert('ATENÇÃO\n\nEste Boletim de Urna já foi cadastrado e não foi somado novamente.\n\nClique em OK, afaste este QR da câmera e aponte para o próximo BU.');lastCode=raw;lastAt=Date.now();requireClearFrame=true;clearFrames=0;$('#cameraMsg').textContent='BU duplicado ignorado. Afaste o QR da câmera para liberar a próxima leitura.';}}catch(e){$('#cameraMsg').textContent=e.message}finally{setTimeout(()=>{scanPaused=false},1800)}}
$('#camera').onclick=async()=>{try{if(!window.isSecureContext)throw Error('A câmera exige HTTPS.');if(!navigator.mediaDevices?.getUserMedia)throw Error('Este navegador não disponibiliza acesso à câmera. Use “Ler QR por foto”.');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});let v=$('#video');v.srcObject=stream;v.classList.remove('hidden');await v.play();$('#cameraMsg').textContent='Câmera ativa. Aponte para o QR Code do BU e mantenha-o centralizado.';let canvas=$('#scanCanvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});timer=setInterval(async()=>{try{if(v.readyState<2)return;let w=v.videoWidth,h=v.videoHeight;if(!w||!h)return;let scale=Math.min(1,900/w);canvas.width=Math.round(w*scale);canvas.height=Math.round(h*scale);ctx.drawImage(v,0,0,canvas.width,canvas.height);let im=ctx.getImageData(0,0,canvas.width,canvas.height);if(typeof jsQR==='function'){let code=jsQR(im.data,im.width,im.height,{inversionAttempts:'attemptBoth'});if(requireClearFrame){if(code?.data){clearFrames=0}else if(++clearFrames>=3){requireClearFrame=false;clearFrames=0;lastCode='';$('#cameraMsg').textContent='Câmera liberada. Aponte para o próximo QR Code.'}return}if(code?.data)await onDecoded(code.data)}else{$('#cameraMsg').textContent='Leitor QR não carregado. Verifique a internet ou use “Ler QR por foto”.'}}catch(e){}},300)}catch(e){stopCamera();$('#cameraMsg').textContent=e.name==='NotAllowedError'?'Permissão da câmera negada. Autorize a câmera para este site e recarregue a página.':e.message}};
$('#stop').onclick=stopCamera;
$('#qrPhoto').onchange=async e=>{try{let f=e.target.files?.[0];if(!f)return;if(typeof jsQR!=='function')throw Error('O leitor QR não carregou.');let bmp=await createImageBitmap(f),canvas=$('#scanCanvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});let scale=Math.min(1,1600/bmp.width);canvas.width=Math.round(bmp.width*scale);canvas.height=Math.round(bmp.height*scale);ctx.drawImage(bmp,0,0,canvas.width,canvas.height);let im=ctx.getImageData(0,0,canvas.width,canvas.height),code=jsQR(im.data,im.width,im.height,{inversionAttempts:'attemptBoth'});if(!code?.data)throw Error('Não consegui identificar um QR Code nessa foto.');await onDecoded(code.data)}catch(err){$('#cameraMsg').textContent=err.message}finally{e.target.value=''}};
function download(name,type,text){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#json').onclick=()=>download('auditabu-2026.json','application/json',JSON.stringify(db,null,2));
$('#xlsx').onclick=()=>{if(typeof XLSX==='undefined'){alert('Biblioteca do Excel não carregou. Verifique a conexão e tente novamente.');return}let detail=[],tot={};for(let b of db.bus)for(let[c,v]of Object.entries(b.votes)){for(let[n,q]of Object.entries(v.nominal)){let ci=candidateInfo(c,n,b.meta.uf);detail.push({UF:b.meta.uf,Municipio:b.meta.muni,Zona:b.meta.zona,Secao:b.meta.secao,Urna:b.meta.urna,Turno:b.meta.turno,Cargo:offices[c]||('Cargo '+c),Numero:n,Candidato:ci.nome,Partido:ci.partido,Votos:q});let k=[b.meta.uf,c,n].join('|');if(!tot[k])tot[k]={UF:b.meta.uf,Cargo:offices[c]||('Cargo '+c),Numero:n,Candidato:ci.nome,Partido:ci.partido,Votos:0};tot[k].Votos+=q}detail.push({UF:b.meta.uf,Municipio:b.meta.muni,Zona:b.meta.zona,Secao:b.meta.secao,Urna:b.meta.urna,Turno:b.meta.turno,Cargo:offices[c]||('Cargo '+c),Numero:'',Candidato:'BRANCOS',Partido:'',Votos:v.branco});detail.push({UF:b.meta.uf,Municipio:b.meta.muni,Zona:b.meta.zona,Secao:b.meta.secao,Urna:b.meta.urna,Turno:b.meta.turno,Cargo:offices[c]||('Cargo '+c),Numero:'',Candidato:'NULOS',Partido:'',Votos:v.nulo})}let wb=XLSX.utils.book_new(),ws1=XLSX.utils.json_to_sheet(detail),ws2=XLSX.utils.json_to_sheet(Object.values(tot).sort((a,b)=>a.Cargo.localeCompare(b.Cargo)||b.Votos-a.Votos));ws1['!cols']=[{wch:5},{wch:18},{wch:8},{wch:9},{wch:12},{wch:7},{wch:25},{wch:10},{wch:35},{wch:15},{wch:12}];ws2['!cols']=[{wch:5},{wch:25},{wch:10},{wch:35},{wch:15},{wch:12}];XLSX.utils.book_append_sheet(wb,ws1,'BUs - Detalhado');XLSX.utils.book_append_sheet(wb,ws2,'Totalizacao');XLSX.writeFile(wb,'AuditaBU_2026.xlsx')};$('#wipe').onclick=()=>{if(confirm('Apagar TODOS os BUs armazenados neste aparelho?')){db={bus:[],pending:{},alerts:[]};save()}};
$('#candidateTemplate').onclick=()=>download('modelo-candidatos.csv','text/csv;charset=utf-8','\ufeffcargo,numero,nome,partido,uf\n1,00,Nome do candidato,PARTIDO,BR\n');$('#candidateFile').onchange=async e=>{let f=e.target.files?.[0];if(!f)return;let txt=await f.text(),lines=txt.replace(/^\ufeff/,'').split(/\r?\n/).filter(Boolean),head=lines.shift().split(',').map(x=>x.trim().toLowerCase());for(let l of lines){let a=l.split(','),o=Object.fromEntries(head.map((h,i)=>[h,(a[i]||'').trim()]));if(o.cargo&&o.numero)candidates[[o.cargo,o.numero,o.uf||''].join('|')]=`${o.nome||('Opção '+o.numero)}${o.partido?' — '+o.partido:''}`}localStorage.setItem(CKEY,JSON.stringify(candidates));$('#candidateMsg').textContent=`Cadastro carregado: ${Object.keys(candidates).length} registros.`;renderTotals()};$('#clearCandidates').onclick=()=>{candidates={};localStorage.removeItem(CKEY);$('#candidateMsg').textContent='Cadastro removido.';renderTotals()};

function exportControleEleitoral(){
 if(typeof XLSX==='undefined'){alert('Biblioteca do Excel não carregou.');return}
 const bus=db.bus.filter(b=>!b.meta.uf||b.meta.uf==='SP'); if(!bus.length){alert('Não há BUs de SP para exportar.');return}
 const bm='55855', cargo='7';
 const sections=bus.slice().sort((x,y)=>(+x.meta.secao||0)-(+y.meta.secao||0));
 const entrada=[['CONTROLE DE VOTAÇÃO — BARROS MUNHOZ (BM)'],['Dados extraídos automaticamente dos Boletins de Urna capturados.'],[],['SEÇÃO','ESCOLA DE VOTAÇÃO','COMPARECIMENTO','VOTOS VÁLIDOS','VOTOS BM']];
 for(const b of sections){let v=b.votes[cargo]||{}, valid=Object.values(v.nominal||{}).reduce((t,q)=>t+(+q||0),0);entrada.push([String(+b.meta.secao||b.meta.secao),(window.AUDITABU_ESCOLAS||{})[String(+b.meta.secao||b.meta.secao)]||'NÃO CADASTRADA',v.total||'',valid,v.nominal?.[bm]||0])}
 const bySchool={}; for(const r of entrada.slice(4)){let s=r[1];bySchool[s]??={n:0,comp:0,val:0,bm:0};let o=bySchool[s];o.n++;o.comp+=+r[2]||0;o.val+=+r[3]||0;o.bm+=+r[4]||0}
 const par=[['RESULTADOS PARCIAIS POR ESCOLA — BARROS MUNHOZ'],['Percentuais calculados sobre as urnas/seções já apuradas.'],[],['ESCOLA','SEÇÕES APURADAS','COMPARECIMENTO','VOTOS VÁLIDOS','VOTOS BM','% BM / VÁLIDOS','% BM / COMPARECIMENTO']];
 Object.keys(bySchool).sort().forEach(s=>{let o=bySchool[s];par.push([s,o.n,o.comp,o.val,o.bm,o.val?o.bm/o.val:0,o.comp?o.bm/o.comp:0])});
 const comp=entrada.slice(4).reduce((t,r)=>t+(+r[2]||0),0), valid=entrada.slice(4).reduce((t,r)=>t+(+r[3]||0),0), bmTot=entrada.slice(4).reduce((t,r)=>t+(+r[4]||0),0);
 par.push(['TOTAL GERAL',sections.length,comp,valid,bmTot,valid?bmTot/valid:0,comp?bmTot/comp:0]);
 const ap=[['APURAÇÃO — BARROS MUNHOZ'],[],['INDICADOR','TOTAL','PERCENTUAL SOBRE URNAS APURADAS'],['URNAS/SEÇÕES APURADAS',sections.length,''],['COMPARECIMENTO',comp,'100%'],['VOTOS VÁLIDOS',valid,comp?valid/comp:0],['VOTOS BM',bmTot,comp?bmTot/comp:0],['% BM SOBRE VOTOS VÁLIDOS','',valid?bmTot/valid:0]];
 let w=XLSX.utils.book_new(),ws1=XLSX.utils.aoa_to_sheet(entrada),ws2=XLSX.utils.aoa_to_sheet(par),ws3=XLSX.utils.aoa_to_sheet(ap);
 ws1['!cols']=[{wch:10},{wch:32},{wch:18},{wch:18},{wch:14}];ws2['!cols']=[{wch:32},{wch:18},{wch:18},{wch:18},{wch:14},{wch:18},{wch:22}];ws3['!cols']=[{wch:30},{wch:18},{wch:30}];
 for(let r=4;r<par.length;r++){ws2['F'+(r+1)]&&(ws2['F'+(r+1)].z='0.00%');ws2['G'+(r+1)]&&(ws2['G'+(r+1)].z='0.00%')}
 ['C6','C7','C8'].forEach(c=>{if(ws3[c])ws3[c].z='0.00%'});
 XLSX.utils.book_append_sheet(w,ws1,'ENTRADA DE DADOS');XLSX.utils.book_append_sheet(w,ws2,'PARCIAIS POR ESCOLA');XLSX.utils.book_append_sheet(w,ws3,'APURAÇÃO');
 XLSX.writeFile(w,'CONTROLE_VOTACAO_BM_3_PLANILHAS.xlsx')
}

if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();refreshCentral();setInterval(refreshCentral,5000);window.addEventListener('focus',refreshCentral);

const authClient=(window.supabase&&window.supabase.createClient)?window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY):null;
async function loadAdmin(){
 if(!authClient)return;
 const {data:{session}}=await authClient.auth.getSession();
 if(!session){$('#adminLogin')?.classList.remove('hidden');$('#adminPanel')?.classList.add('hidden');return}
 const {data:ok}=await authClient.from('admin_users').select('email').eq('email',session.user.email).maybeSingle();
 if(!ok){$('#adminMsg').textContent='Conta autenticada, mas este e-mail ainda não está autorizado como administrador.';await authClient.auth.signOut();return}
 $('#adminLogin').classList.add('hidden');$('#adminPanel').classList.remove('hidden');$('#adminWho').textContent=session.user.email;
 const {data, error}=await authClient.from('boletins').select('received_at,uf,municipio,zona,secao,urna,device_id').order('received_at',{ascending:false});
 if(error){$('#adminMsg').textContent='Não foi possível carregar a base central.';return}
 $('#adminBU').textContent=data.length;$('#adminSec').textContent=new Set(data.map(x=>[x.uf,x.zona,x.secao].join('|'))).size;
 $('#adminRows').innerHTML=data.map(x=>'<tr><td>'+esc(new Date(x.received_at).toLocaleString('pt-BR'))+'</td><td>'+esc(x.uf)+'</td><td>'+esc(x.municipio)+'</td><td>'+esc(x.zona)+'</td><td>'+esc(x.secao)+'</td><td>'+esc(x.urna)+'</td><td>'+esc(x.device_id)+'</td></tr>').join('');
 $('#adminMsg').textContent='Base central carregada.';
}
if($('#adminEnter'))$('#adminEnter').onclick=async()=>{try{let email=$('#adminEmail').value.trim(),password=$('#adminPass').value;let {error}=await authClient.auth.signInWithPassword({email,password});if(error)throw error;await loadAdmin()}catch(e){$('#adminMsg').textContent='Não foi possível entrar: '+e.message}};
if($('#adminCreate'))$('#adminCreate').onclick=async()=>{const email=$('#adminEmail').value.trim(),password=$('#adminPass').value;if(!email||!password){$('#adminMsg').textContent='Informe o e-mail e a senha que deseja criar.';return}if(password.length<6){$('#adminMsg').textContent='A senha deve ter pelo menos 6 caracteres.';return}const {data,error}=await authClient.auth.signUp({email,password,options:{emailRedirectTo:'https://lhsartorelli.github.io/auditabu-2026/'}});if(error){$('#adminMsg').textContent='Não foi possível criar a senha: '+error.message;return}if(data.session){$('#adminMsg').textContent='Senha criada. Acessando o painel…';await loadAdmin()}else $('#adminMsg').textContent='Cadastro realizado. Verifique o e-mail para confirmar a conta e depois clique em Entrar.'};
if($('#adminForgot'))$('#adminForgot').onclick=async()=>{const email=$('#adminEmail').value.trim();if(!email){$('#adminMsg').textContent='Informe primeiro seu e-mail.';return}const {error}=await authClient.auth.resetPasswordForEmail(email,{redirectTo:'https://lhsartorelli.github.io/auditabu-2026/'});$('#adminMsg').textContent=error?('Não foi possível enviar a recuperação: '+error.message):'Link de recuperação enviado para '+email+'.'};
if($('#adminExit'))$('#adminExit').onclick=async()=>{await authClient.auth.signOut();await loadAdmin()};
if($('#adminRefresh'))$('#adminRefresh').onclick=loadAdmin;
setTimeout(loadAdmin,0);
